# Generated by Django 3.0.5 on 2020-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cnic', models.CharField(max_length=14, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6)),
                ('surgery', models.CharField(max_length=100)),
                ('surgery_date', models.DateField()),
                ('recovery_date', models.DateField()),
            ],
            options={
                'ordering': ('-surgery_date',),
            },
        ),
    ]
