# Generated by Django 3.0.5 on 2020-07-09 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 7, 9, 13, 9, 9, 857572, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='surgery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
