# Generated by Django 3.0.5 on 2020-07-13 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 7, 13, 7, 50, 48, 4417, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
