# Generated by Django 3.0.5 on 2020-07-13 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='surgery_details',
            field=models.TextField(default=datetime.datetime(2020, 7, 13, 9, 19, 45, 610837, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
