# Generated by Django 3.0.5 on 2020-07-13 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_surgery_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'MARRIED'), ('Divorced', 'DIVORCED'), ('Single', 'SINGLE'), ('Engaged', 'ENGAGED')], default=datetime.datetime(2020, 7, 13, 10, 19, 26, 454013, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
