# Generated by Django 3.0.5 on 2020-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
